# Generated by Django 5.1.2 on 2024-10-28 22:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('senha', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20, unique=True)),
                ('endereco', models.CharField(max_length=200)),
                ('perfilUsuario', models.CharField(max_length=20)),
                ('nomeOrganizacao', models.CharField(blank=True, max_length=200, null=True)),
                ('dataCadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastEdit', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO')], default='ATIVO', max_length=7)),
            ],
            options={
                'db_table': 'foodConnect_usuario',
            },
        ),
    ]
