# Generated by Django 5.1.2 on 2024-10-28 22:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodConnect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('idProduto', models.AutoField(primary_key=True, serialize=False)),
                ('imagem', models.CharField(max_length=255, unique=True)),
                ('descricao', models.CharField(max_length=200)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unidade', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('DISPONÍVEL', 'DISPONÍVEL'), ('INDISPONÍVEL', 'INDISPONÍVEL'), ('DOADO', 'DOADO')], default='DISPONÍVEL', max_length=15)),
                ('dataPostagem', models.DateTimeField(default=django.utils.timezone.now)),
                ('idDoador', models.ForeignKey(db_column='idDoador', on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='foodConnect.usuario')),
            ],
            options={
                'db_table': 'foodConnect_produto',
            },
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('idDoacao', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('dataDoacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('idDoador', models.ForeignKey(db_column='idDoador', on_delete=django.db.models.deletion.CASCADE, related_name='doacoes_doador', to='foodConnect.usuario')),
                ('idReceptor', models.ForeignKey(db_column='idReceptor', on_delete=django.db.models.deletion.CASCADE, related_name='doacoes_receptor', to='foodConnect.usuario')),
                ('idProduto', models.ForeignKey(db_column='idProduto', on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='foodConnect.produto')),
            ],
            options={
                'db_table': 'foodConnect_doacao',
            },
        ),
    ]
